project_path: /tmp/eagle_agent/
eagle_db_test:
    mysql_ip: 127.0.0.1
    mysql_user: root
    mysql_port: 3306
    mysql_db: eagle_agent
    mysql_pass: fffjjj
eagle_db_pro:
    mysql_ip: 127.0.0.1
    mysql_user: root
    mysql_port: 3306
    mysql_db: eagle_agent
    mysqlpass: fffjjj
