version: 1
formatters:
  simple:
    format: '[%(process)d:%(thread)d:%(levelname)s:%(asctime)s:%(filename)s(%(lineno)d)] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  info_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    filename: /tmp/agent.log
    backupCount: 5
    when: D
    interval: 1
    encoding: 'utf-8'
  error_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: ERROR
    formatter: simple
    filename: /tmp/agent.log
    backupCount: 8
    when: D
    interval: 1
    encoding: 'utf-8'

loggers:
  simpleExample:
    level: DEBUG
    handlers: [console]
    propagate: no
  agent_logger:
    level: DEBUG
    handlers: [info_handler]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
